# =========================
# Task 01 - MQTT (1883)
# Unencrypted / Unauthenticated
# =========================
listener 1883
allow_anonymous true


# =========================
# Task 02 - MQTT (1884)
# Unencrypted / Authenticated
# =========================
listener 1884
allow_anonymous false
password_file /mosquitto/config/passwd


# =========================
# Task 03 - MQTT TLS (8883)
# Encrypted / Unauthenticated
# =========================
listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
allow_anonymous true


# =========================
# Task 04 - Mutual TLS (8884)
# Encrypted / Client Certificate Required
# =========================
listener 8884
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate true
use_identity_as_username false
allow_anonymous true


# =========================
# Task 05 - TLS + Authentication (8885)
# Encrypted / Username Password
# =========================
listener 8885
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
allow_anonymous false
password_file /mosquitto/config/passwd


# =========================
# Task 06 - TLS (8886)
# Encrypted / No Authentication
# =========================
listener 8886
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
allow_anonymous true


